Name: CI-Python-App

on:
	push:
		branches: [main]
	pull_requests:
		branches: [main]

jobs:
	Analyze:
		runs-on: ubuntu-latest
		
		Steps:
			- uses: actions/checkout@v4
		
			- Name: Setup Python
			uses: actions/setup-python@v5.2.0
			with:
				python-version: 3.11
		
			- Name: Install Packages
			run: |
				Python3 -m pip install --upgrade pip
				Pip install -r requirements.txt
			
			- Name: Analyze Code using pylint
			run:
				Pylint app.py
