name: Deploy Streamlit App
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: '3.11'

      - name: Install Packages
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Analyze Code using pylint
      #   run: |
      #     pylint app.py

  Setting-Up:
    runs-on: ubuntu-latest
    needs: [Analyze]
        
    steps:
      - uses: actions/checkout@v4

      - name: Create PEM file
        run: |
          echo "${{ secrets.SERVER_PEM }}" > server-key.pem
          chmod 400 server-key.pem  # Set permissions
          
      - name: Connect to EC2 and execute commands
        run: |
          ssh -i server-key.pem ubuntu@${{ secrets.SERVER_IP }} << 'EOF'
          git clone https://github.com/hussein-turfah/DevOps-Recipe-Finder.git
          cd /home/ubuntu/DevOps-Recipe-Finder
          git pull origin main
          EOF
